![imagenes](logo.png)

# Diagonalización

## Definición de eigenvalores y eigenvectores

Sea $A$ una matriz cuadrada de tamaño $n \times n$. Un **eigenvector** de $A$ es un vector no nulo $\mathbf{v} \in \mathbb{R}^n$ tal que:

$$A \mathbf{v} = \lambda \mathbf{v}$$

donde $\lambda \in \mathbb{R}$ (o $\mathbb{C}$) es un escalar llamado **eigenvalor** (o valor propio) asociado a $\mathbf{v}$.

**Interpretación geométrica:**  
Multiplicar la matriz $A$ por su eigenvector $\mathbf{v}$ produce un vector que es un múltiplo escalar de $\mathbf{v}$. Es decir, la dirección de $\mathbf{v}$ permanece invariante bajo la transformación lineal representada por $A$; sólo su longitud y posiblemente su sentido se ven alterados por el factor $\lambda$.

**Ejemplo:**  
Sea $A = \begin{pmatrix} 2 & 1 \\ 1 & 2 \end{pmatrix}$. Verifiquemos que $\mathbf{v} = (1, 1)^\top$ es un eigenvector:

$$A \mathbf{v} = \begin{pmatrix} 2 & 1 \\ 1 & 2 \end{pmatrix} \begin{pmatrix} 1 \\ 1 \end{pmatrix} = \begin{pmatrix} 3 \\ 3 \end{pmatrix} = 3 \begin{pmatrix} 1 \\ 1 \end{pmatrix}$$

Por lo tanto, $\lambda = 3$ es el eigenvalor asociado a $\mathbf{v}$.

## Cálculo de eigenvalores

La ecuación $A \mathbf{v} = \lambda \mathbf{v}$ puede reescribirse como:

$$(A - \lambda I) \mathbf{v} = 0$$

Dado que $\mathbf{v} \neq \mathbf{0}$, la matriz $(A - \lambda I)$ debe ser **singular** (no invertible). Esto equivale a que su determinante sea cero:

$$\det(A - \lambda I) = 0$$

Esta ecuación se denomina **ecuación característica** de $A$. El polinomio $p(\lambda) = \det(A - \lambda I)$ es el **polinomio característico** de $A$. Sus raíces son los eigenvalores de $A$.

**Ejemplo (continuación):**  
Para $A = \begin{pmatrix} 2 & 1 \\ 1 & 2 \end{pmatrix}$:

$$A - \lambda I = \begin{pmatrix} 2-\lambda & 1 \\ 1 & 2-\lambda \end{pmatrix}$$

$$\det(A - \lambda I) = (2-\lambda)^2 - 1 = \lambda^2 - 4\lambda + 3 = (\lambda - 3)(\lambda - 1)$$

Por lo tanto, los eigenvalores son $\lambda_1 = 3$ y $\lambda_2 = 1$.

In [1]:
import numpy as np

A = np.array([[2, 1],
              [1, 2]])

# Cálculo numérico de eigenvalores y eigenvectores
eigenvals, eigenvecs = np.linalg.eig(A)

print("Eigenvalores:", eigenvals)
print("Eigenvectores (columnas):\n", eigenvecs)

Eigenvalores: [3. 1.]
Eigenvectores (columnas):
 [[ 0.70710678 -0.70710678]
 [ 0.70710678  0.70710678]]


In [2]:
v = eigenvecs[:, 0]  # primer eigenvector
l = eigenvals[0]     # primer eigenvalor

print("A @ v:", A @ v)
print("l * v:", l * v)
print("Iguales?", np.allclose(A @ v, l * v))

A @ v: [2.12132034 2.12132034]
l * v: [2.12132034 2.12132034]
Iguales? True


## Propiedades de eigenvalores y eigenvectores

**Propiedades generales:**

1. **Traza:** $\text{tr}(A) = \lambda_1 + \lambda_2 + \dots + \lambda_n$  
   (suma de eigenvalores, contando multiplicidades).

2. **Determinante:** $\det(A) = \lambda_1 \lambda_2 \cdots \lambda_n$  
   (producto de eigenvalores, contando multiplicidades).

3. **Polinomio característico:** $p(\lambda) = \det(A - \lambda I)$.

4. **Multiplicidad algebraica:** Número de veces que un eigenvalor aparece como raíz del polinomio característico.

5. **Multiplicidad geométrica:** Dimensión del espacio propio asociado a un eigenvalor, es decir, $\dim \ker(A - \lambda I)$.

**Relaciones importantes:**

- La multiplicidad geométrica **nunca excede** la multiplicidad algebraica.
- Si para algún eigenvalor la multiplicidad geométrica es **estrictamente menor** que la algebraica, la matriz es **defectuosa** (no diagonalizable).
- Eigenvectores asociados a eigenvalores **distintos** son siempre linealmente independientes.

In [3]:
print("Traza (suma):", np.trace(A), "≈ suma eigenvals:", sum(eigenvals))
print("Det (producto):", np.linalg.det(A), "≈ producto eigenvals:", np.prod(eigenvals))

Traza (suma): 4 ≈ suma eigenvals: 4.0
Det (producto): 2.9999999999999996 ≈ producto eigenvals: 3.0


## Diagonalización

Una matriz $A \in \mathbb{R}^{n \times n}$ es **diagonalizable** si existe una matriz invertible $P$ y una matriz diagonal $D$ tales que:

$$A = P D P^{-1}$$

En ese caso, las **columnas de $P$** son eigenvectores de $A$, y los **elementos diagonales de $D$** son los eigenvalores correspondientes.

**Condición necesaria y suficiente:**  
$A$ es diagonalizable si y solo si posee $n$ eigenvectores linealmente independientes.  
Equivalentemente, para cada eigenvalor, su multiplicidad geométrica debe coincidir con su multiplicidad algebraica.

### Diagonalización ortogonal (caso simétrico)

Si $A$ es **simétrica** ($A = A^\top$), entonces es diagonalizable mediante una matriz **ortogonal** $Q$ (esto es, $Q^{-1} = Q^\top$):

$$A = Q \Lambda Q^\top$$

donde $\Lambda$ es diagonal (con los eigenvalores) y las columnas de $Q$ son eigenvectores **ortonormales**.

In [4]:
Q = eigenvecs  # para matrices simétricas, np.linalg.eig devuelve Q ortogonal
print("Q^T Q:\n", Q.T @ Q)
print("¿Es identidad?", np.allclose(Q.T @ Q, np.eye(2)))

Q^T Q:
 [[1. 0.]
 [0. 1.]]
¿Es identidad? True


In [5]:
Lambda = np.diag(eigenvals)
A_reconstruida = Q @ Lambda @ Q.T

print("Original A:\n", A)
print("Reconstruida:\n", A_reconstruida)
print("¿Iguales?", np.allclose(A, A_reconstruida))

Original A:
 [[2 1]
 [1 2]]
Reconstruida:
 [[2. 1.]
 [1. 2.]]
¿Iguales? True


## Descomposición espectral (forma expandida)

Para matrices simétricas, la diagonalización ortogonal $A = Q \Lambda Q^\top$ puede reescribirse como una **suma de proyectores ortogonales**:

$$A = \sum_{i=1}^n \lambda_i \, \mathbf{q}_i \mathbf{q}_i^\top$$

donde:
- $\lambda_i$ son los eigenvalores (reales),
- $\mathbf{q}_i$ son los eigenvectores ortonormales (columnas de $Q$).

**Interpretación geométrica:**  
Cada matriz $\mathbf{q}_i \mathbf{q}_i^\top$ es la **proyección ortogonal** sobre la dirección del eigenvector $\mathbf{q}_i$. Así, la descomposición espectral expresa $A$ como una combinación lineal de proyecciones ortogonales, ponderada por los eigenvalores.

**Aplicación en PCA (Análisis de Componentes Principales):**  
En PCA, se calcula la descomposición espectral de la matriz de covarianza (o correlación) de los datos. Los eigenvectores indican las **direcciones de máxima varianza** (componentes principales), y los eigenvalores miden la varianza explicada por cada componente. Esto permite reducir la dimensionalidad preservando la mayor cantidad de información posible.