In [1]:
import numpy as np

Para cualquier vector $b\in\mathbb{R}^n$, el sistema $$Ax=b$$ tiene solución única:

Si la matriz es invertible, entonces $x=A^{-1}b$

**Ejemplo**

$$
A = \begin{pmatrix}
3 & 7 & 2 & 9 & 5 & 1 & 8 & 4 & 6 & 2 \\
5 & 8 & 1 & 4 & 7 & 3 & 9 & 2 & 5 & 7 \\
9 & 2 & 6 & 3 & 8 & 5 & 1 & 7 & 4 & 3 \\
1 & 5 & 4 & 7 & 2 & 9 & 3 & 6 & 8 & 5 \\
7 & 3 & 8 & 1 & 6 & 4 & 2 & 9 & 3 & 1 \\
4 & 9 & 3 & 6 & 1 & 7 & 5 & 8 & 2 & 9 \\
6 & 1 & 7 & 5 & 9 & 2 & 4 & 3 & 7 & 6 \\
2 & 4 & 9 & 8 & 3 & 6 & 7 & 1 & 9 & 4 \\
8 & 6 & 5 & 2 & 4 & 1 & 6 & 5 & 2 & 8 \\
3 & 7 & 2 & 4 & 5 & 8 & 1 & 6 & 3 & 5
\end{pmatrix}
$$

In [2]:
import numpy as np

A = np.array([
    [3, 7, 2, 9, 5, 1, 8, 4, 6, 2],
    [5, 8, 1, 4, 7, 3, 9, 2, 5, 7],
    [9, 2, 6, 3, 8, 5, 1, 7, 4, 3],
    [1, 5, 4, 7, 2, 9, 3, 6, 8, 5],
    [7, 3, 8, 1, 6, 4, 2, 9, 3, 1],
    [4, 9, 3, 6, 1, 7, 5, 8, 2, 9],
    [6, 1, 7, 5, 9, 2, 4, 3, 7, 6],
    [2, 4, 9, 8, 3, 6, 7, 1, 9, 4],
    [8, 6, 5, 2, 4, 1, 6, 5, 2, 8],
    [3, 7, 2, 4, 5, 8, 1, 6, 3, 5]
])

A

array([[3, 7, 2, 9, 5, 1, 8, 4, 6, 2],
       [5, 8, 1, 4, 7, 3, 9, 2, 5, 7],
       [9, 2, 6, 3, 8, 5, 1, 7, 4, 3],
       [1, 5, 4, 7, 2, 9, 3, 6, 8, 5],
       [7, 3, 8, 1, 6, 4, 2, 9, 3, 1],
       [4, 9, 3, 6, 1, 7, 5, 8, 2, 9],
       [6, 1, 7, 5, 9, 2, 4, 3, 7, 6],
       [2, 4, 9, 8, 3, 6, 7, 1, 9, 4],
       [8, 6, 5, 2, 4, 1, 6, 5, 2, 8],
       [3, 7, 2, 4, 5, 8, 1, 6, 3, 5]])

Para saber si es invertible.

**Teorema importante**

Tomemos $A$ una matriz (no necesariamente cuadrada) donde todas sus columnas son linealmente independientes. Entonces la matriz $A^TA$ es invertible.






**Observación** Si $X$ tiene $m$ filas y $n$ columnas y $Y$ tiene $n$ filas y $r$ columnas, entonces $XY$ existe y tiene $m$ filas y $r$ columnas

*Demostración*

Que una matriz sea invertible equivale a que su kernel es el vector $\{0\}$. Por lo tanto quiero ver que $\mathrm{Ker}(A^TA)=\{0\}$.

Sea $u$ un elemento de $\mathrm{Ker}(A^TA)$. Como está en el kernel, $A^TAu=0$

Recordemos que si $M$ es matriz y $x$ y $y$ son vectores, entonces $$\langle x,My\rangle=\langle M^Tx,y\rangle$$

Notemos que $0=\langle u,A^TAu\rangle=\langle Au,Au\rangle=\|Au\|^2$. 

Concluyo que $Au=0$. Ahora, como las columnas de $A$ son linealmente independientes, oor lo tanto $u=0$

**Ejemplo 4**

El sistema $$\left\{\begin{array}{ccc}x+2y&=&5\\2x-y&=&0\\3x+y&=&5\end{array}\right.$$

La matriz es $$A=\begin{pmatrix}1&2\\2&-1\\3&1\end{pmatrix}$$ y por lo tanto el rango es 2

La matriz aumentada es $$[A|b]=\begin{pmatrix}1&2&5\\2&-1&0\\3&1&5\end{pmatrix}$$

Observa que $col3=col1+2\cdot col2$. Por lo tanto el rango de $[A|b]$ es 2

**Fenómeno importante: infintas soluciones**

Supongamos que $Ax=b$ tiene infinitas soluciones. ¿Cómo se construyen esas infinitas soluciones?

Sea $x_0$ cualquier solución del sistema $Ax=b$. Es decir, $x_0$ es un vector que cumple $Ax_0=b$.

Observa el sistema $Ax=0$. A este se llama *sistema homogéneo asociado*



**Cualquier solución del sistema Ax=b es de la forma**

$$x=x_0+x_h$$ donde $x_h$ es una solución cualquiera de $Ax=0$

Sol = x0 + Ker(A)

$$\begin{pmatrix}1&1\\1&0\end{pmatrix}$$

In [26]:
import numpy as np

def analizar_sistema(A, b):
    """Analiza el sistema Ax = b. A y b deben ser np.array"""
   
    # Aseguramos que b sea columna
    b_col = b.reshape(-1, 1)
   
    # Matriz aumentada
    Ab = np.hstack((A, b_col))
   
    rank_A = np.linalg.matrix_rank(A)
    rank_Ab = np.linalg.matrix_rank(Ab)
    n = A.shape[1]
   
    print("=== Análisis del sistema Ax = b ===")
    print(f"Rango de A      : {rank_A}")
    print(f"Rango de [A|b]  : {rank_Ab}")
    print(f"Número de variables : {n}\n")
   
    if rank_A < rank_Ab:
        print("→ El sistema NO tiene solución (inconsistente)")
        return None
   
    elif rank_A == n:
        print("→ El sistema tiene solución ÚNICA")
        x, residuos, rango, s = np.linalg.lstsq(A, b.ravel(),rcond=None)
        print("Solución x =", np.round(x, decimals=8))
        return x
    
    else:
        print("→ El sistema tiene INFINITAS soluciones")
        # Solución particular
        x_part = np.linalg.lstsq(A, b.ravel(), rcond=None)[0]
        print("Una solución particular x =", np.round(x_part, decimals=8))
        
        # Dimensión del kernel
        dim_kernel = n - rank_A
        print(f"   (Hay {dim_kernel} variable(s) libre(s))")
        
        # Base para el kernel (espacio nulo)
        if dim_kernel > 0:
            print("\nBase para el kernel (espacio nulo de A):")
            # Usamos SVD para obtener una base del kernel
            _, _, Vt = np.linalg.svd(A, full_matrices=True)
            kernel_basis = Vt[-dim_kernel:]   # últimas filas de Vt
            for i in range(dim_kernel):
                print(f"v{i+1} =", np.round(kernel_basis[i], decimals=8))
        
        return x_part,kernel_basis

In [25]:
A = np.array([[1,2],
              [2,-1],
              [3,1]
              ])
    
b = np.array([5,0,5])

analizar_sistema(A,b)


=== Análisis del sistema Ax = b ===
Rango de A      : 2
Rango de [A|b]  : 2
Número de variables : 2

→ El sistema tiene solución ÚNICA
Solución x = [1. 2.]


array([1., 2.])

In [27]:
A = np.array([[1,1],
              [2,2]
             ])

b = np.array([2,4])

analizar_sistema(A,b)

=== Análisis del sistema Ax = b ===
Rango de A      : 1
Rango de [A|b]  : 1
Número de variables : 2

→ El sistema tiene INFINITAS soluciones
Una solución particular x = [1. 1.]
   (Hay 1 variable(s) libre(s))

Base para el kernel (espacio nulo de A):
v1 = [-0.70710678  0.70710678]


(array([1., 1.]), array([[-0.70710678,  0.70710678]]))

Lo anterior me dice que cualquier solución de sistema es 
$$x=\begin{pmatrix}1\\1\end{pmatrix}$$



